// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/rplace.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCanvasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCanvasRequest) Reset() {
	*x = GetCanvasRequest{}
	mi := &file_proto_rplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCanvasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCanvasRequest) ProtoMessage() {}

func (x *GetCanvasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCanvasRequest.ProtoReflect.Descriptor instead.
func (*GetCanvasRequest) Descriptor() ([]byte, []int) {
	return file_proto_rplace_proto_rawDescGZIP(), []int{0}
}

type Pixel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         int32                  `protobuf:"varint,1,opt,name=color,proto3" json:"color,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pixel) Reset() {
	*x = Pixel{}
	mi := &file_proto_rplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pixel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pixel) ProtoMessage() {}

func (x *Pixel) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pixel.ProtoReflect.Descriptor instead.
func (*Pixel) Descriptor() ([]byte, []int) {
	return file_proto_rplace_proto_rawDescGZIP(), []int{1}
}

func (x *Pixel) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *Pixel) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pixel) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PlacePixelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacePixelResponse) Reset() {
	*x = PlacePixelResponse{}
	mi := &file_proto_rplace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacePixelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacePixelResponse) ProtoMessage() {}

func (x *PlacePixelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rplace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacePixelResponse.ProtoReflect.Descriptor instead.
func (*PlacePixelResponse) Descriptor() ([]byte, []int) {
	return file_proto_rplace_proto_rawDescGZIP(), []int{2}
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pixels        []uint32               `protobuf:"varint,1,rep,packed,name=pixels,proto3" json:"pixels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_proto_rplace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rplace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_proto_rplace_proto_rawDescGZIP(), []int{3}
}

func (x *Row) GetPixels() []uint32 {
	if x != nil {
		return x.Pixels
	}
	return nil
}

type Canvas struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grid          []*Row                 `protobuf:"bytes,1,rep,name=grid,proto3" json:"grid,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Canvas) Reset() {
	*x = Canvas{}
	mi := &file_proto_rplace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Canvas) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Canvas) ProtoMessage() {}

func (x *Canvas) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rplace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Canvas.ProtoReflect.Descriptor instead.
func (*Canvas) Descriptor() ([]byte, []int) {
	return file_proto_rplace_proto_rawDescGZIP(), []int{4}
}

func (x *Canvas) GetGrid() []*Row {
	if x != nil {
		return x.Grid
	}
	return nil
}

func (x *Canvas) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_proto_rplace_proto protoreflect.FileDescriptor

const file_proto_rplace_proto_rawDesc = "" +
	"\n" +
	"\x12proto/rplace.proto\x12\frplace_clone\"\x12\n" +
	"\x10GetCanvasRequest\"9\n" +
	"\x05Pixel\x12\x14\n" +
	"\x05color\x18\x01 \x01(\x05R\x05color\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\"\x14\n" +
	"\x12PlacePixelResponse\"\x1d\n" +
	"\x03Row\x12\x16\n" +
	"\x06pixels\x18\x01 \x03(\rR\x06pixels\"C\n" +
	"\x06Canvas\x12%\n" +
	"\x04grid\x18\x01 \x03(\v2\x11.rplace_clone.RowR\x04grid\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size2\x97\x01\n" +
	"\rCanvasService\x12A\n" +
	"\tGetCanvas\x12\x1e.rplace_clone.GetCanvasRequest\x1a\x14.rplace_clone.Canvas\x12C\n" +
	"\n" +
	"PlacePixel\x12\x13.rplace_clone.Pixel\x1a .rplace_clone.PlacePixelResponseB\bZ\x06./grpcb\x06proto3"

var (
	file_proto_rplace_proto_rawDescOnce sync.Once
	file_proto_rplace_proto_rawDescData []byte
)

func file_proto_rplace_proto_rawDescGZIP() []byte {
	file_proto_rplace_proto_rawDescOnce.Do(func() {
		file_proto_rplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rplace_proto_rawDesc), len(file_proto_rplace_proto_rawDesc)))
	})
	return file_proto_rplace_proto_rawDescData
}

var file_proto_rplace_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_rplace_proto_goTypes = []any{
	(*GetCanvasRequest)(nil),   // 0: rplace_clone.GetCanvasRequest
	(*Pixel)(nil),              // 1: rplace_clone.Pixel
	(*PlacePixelResponse)(nil), // 2: rplace_clone.PlacePixelResponse
	(*Row)(nil),                // 3: rplace_clone.Row
	(*Canvas)(nil),             // 4: rplace_clone.Canvas
}
var file_proto_rplace_proto_depIdxs = []int32{
	3, // 0: rplace_clone.Canvas.grid:type_name -> rplace_clone.Row
	0, // 1: rplace_clone.CanvasService.GetCanvas:input_type -> rplace_clone.GetCanvasRequest
	1, // 2: rplace_clone.CanvasService.PlacePixel:input_type -> rplace_clone.Pixel
	4, // 3: rplace_clone.CanvasService.GetCanvas:output_type -> rplace_clone.Canvas
	2, // 4: rplace_clone.CanvasService.PlacePixel:output_type -> rplace_clone.PlacePixelResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_rplace_proto_init() }
func file_proto_rplace_proto_init() {
	if File_proto_rplace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rplace_proto_rawDesc), len(file_proto_rplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rplace_proto_goTypes,
		DependencyIndexes: file_proto_rplace_proto_depIdxs,
		MessageInfos:      file_proto_rplace_proto_msgTypes,
	}.Build()
	File_proto_rplace_proto = out.File
	file_proto_rplace_proto_goTypes = nil
	file_proto_rplace_proto_depIdxs = nil
}
